### PR TITLE
Move default image to alpine

### LINKED ISSUE #206: [Bug] Unstable on high load systems
**Describe the bug**
If the server on which this container is running comes under heavy pressure, processes like ospd-openvas die.

**To Reproduce**
1. Have a big server with muchrum and much CPU
2. Start some scanns
3. Let this run for some days and keep the mashine under pressure, also RAM etc.
4. (you can also do it by hand from HV side - kill `ospd-openvas` like OOM would do....)
4. when you look to the webinterface you will see some about scans and this is the step where you see `ospd-openvas` is died!
5. See error - look into the Container and look for `ospd-openvas` all gone

**Expected behavior**
I recommend Supervisor with an initialization script that monitors and restarts the processes. Without monitoring you don't get to know about dead processes in the container.

**Additional context**
Latest Version and before affacted.

### PR DESCRIPTION
**Pull request by Dexus**
# What does this PR:

- Use the latest Alpine Version under Major Version 3 like 3.14 as of the current date. 
- Fix the "mv: inter-device move failed" error which can occur under certain circumstances.
- Add a initial data.tar.gz - no generator yet created - will follow by seperate PR
- No Symlink-fu keep the setup as simple as possible - maybe this needs a bit discuss -> if symlink MUST be used, it would be good to keep the symlinks as low as possible not every subdir use direct the /var/lib/gvm (home) and /var/lib/openvas/plugins path - also for DB place the DB storage path direct to the volume.
- supervisord support
  - fix #206  
- postfix support

We have two build ways:
With build for initialize on container start (only ~ ~~435~~ 1100MB)

`docker build -f Dockerfile -t securecompliance/gvm:v21.04-latest-nodata -t securecompliance/gvm:latest  .`

or
With pre-initialized that can be used without extra volumes on startup (only ~ 1200MB)

`docker build -f Dockerfile --build-arg SETUP=1 -t securecompliance/gvm:v21.04-latest-withdata -t securecompliance/gvm:latest-withdata  .`

## Milestones:
- [Downsize the GVM Docker Container](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/1)
- [Clean Up start.sh](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/15)
- [Postfix Mail Server for Delivering Email Notices from GVM](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/8)
- [Improve Structure git repo/docker build](https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/milestone/3)

## Fixes ~~not~~ included:
- ~~Increase the web timeout - ref:#115 (bd6b15707e4fb58deeae1a384fc64e661ad82322) -> this can be done if we build the packages by our own~~
- ~~openvas-smb -> custom Build need (available on edge (latest: 21.4.1) -> but currently not for 21.4.1 (latest) -> own repo or should I add this here?~~

(Update: is integrated now via custom apk build)

# **Branking Change:**
- Logs of each service is not pushed to the `docker logs` each service has an own logfile.

### CODE REVIEW

**Comment by Dexus** [comment]
@pixelsquared @austinsonger I would love to get more access to this repos, so I can create some other branches/repos.

So I can create a repo for the custom APK build (#115 )

**Review by austinsonger — APPROVED** [review]
LGTM

**Comment by austinsonger** [comment]
@Dexus 

> @pixelsquared @austinsonger I would love to get more access to this repos, so I can create some other branches/repos.
> 
> So I can create a repo for the custom APK build (#115 )

I'm also working on a permission team scheme right now for the organization and give me a day for that. But I will create a repo right now for the APK build.

**Comment by austinsonger** [comment]
@Dexus  https://github.com/Secure-Compliance-Solutions-LLC/GVM-APK-build

**Comment by Dexus** [comment]
> @Dexus https://github.com/Secure-Compliance-Solutions-LLC/GVM-APK-build

Initial commit is pushed to master branch, includes already the timeout patch.

**Comment by Dexus** [comment]
So I think it is now final.

Let me know what you guys think.

Best Regards, Josef

File: Dockerfile [hunk 1]
```diff
@@ -41,11 +41,22 @@ ENV SUPVISD=${SUPVISD:-supervisorctl} \
...
+    echo 'https://dl-cdn.alpinelinux.org/alpine/v3.14/main/' ; \
+    echo 'https://dl-cdn.alpinelinux.org/alpine/v3.14/community/' ; \
+    } >/etc/apk/repositories \
+    && cat /etc/apk/repositories \
+    && sleep 5 \
+    && apk update --update-cache \
+    && sleep 5 \
+    && apk upgrade --available \
+    && sleep 5 \
+    && apk add --allow-untrusted curl su-exec tzdata postfix mailx bash openssh supervisor openvas@custcom openvas-smb@custcom openvas-config@custcom gvmd@custcom gvm-libs@custcom greenbone-security-assistant@custcom ospd-openvas@custcom \
```
Comment (miyoyo) [inline Dockerfile:59]: This seems to be missing quite a few packages compared to the existing image

Here are the current ubuntu packages:
<details>
bison
build-essential
ca-certificates
cmake
curl
fakeroot
gcc
gcc-mingw-w64
geoip-database
git
gnutls-bin
graphviz
heimdal-dev
ike-scan
libgcrypt20-dev
libglib2.0-dev
libgnutls28-dev
libgpgme11-dev
libgpgme-dev
libhiredis-dev
libical-dev
libksba-dev
libldap2-dev
libmicrohttpd-dev
libnet1-dev
libnet-snmp-perl
libpcap-dev
libpopt-dev
libradcli-dev
libsnmp-dev
libssh-gcrypt-dev
libunistring-dev
libxml2-dev
net-tools
nmap
nsis
openssh-client
openssh-server
perl-base
pkg-config
postfix
postgresql-12
postgresql-server-dev-12
python3-defusedxml
python3-dev
python3-dialog
python3-lxml
python3-paramiko
python3-pip
python3-polib
python3-psutil
python3-setuptools
redis-server
redis-tools
rpm
rsync
smbclient
sshpass
texlive-fonts-recommended
texlive-latex-extra
uuid-dev    
wapiti
wget
whiptail
xml-twig-tools
xsltproc
</details>

Of course, a lot of these are for package builds, so they're not absolutely required, however there are still some which are optional dependencies for GVM, such as Texlive (which is very heavy), xml tools, samba, fakeroot...

Here is the best I could come up with on my own, there are still things missing, such as wapiti and nsis:
```
    echo 'http://dl-3.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories && \ 
    echo 'http://dl-3.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
    apk upgrade --update-cache --available && \
    apk add \
    gvmd greenbone-security-assistant openvas gvm-tools\
    openvas-smb ospd-openvas py3-gvm \
    texlive \
    libxslt xmlstarlet zip \
    fakeroot \
    rpm \
    dpkg \
    gnupg \
    wget \
    openssh sshpass \
    socat \
    net-snmp-tools \
    samba-client \
    py3-lxml \
    gnutls-utils \
    perl-xml-twig
```
These are using the edge community packages (which is probably against the philosophy of this project).

This was in order to get an idea of the weight with all additional packages: 410MB without Texlive, 927MB with Texlive, so you may want to split Texlive off to either an optional switch, or a separate image.

File: Dockerfile [hunk 2]
```diff
@@ -1,161 +1,101 @@
...
+    echo 'https://dl-4.alpinelinux.org/alpine/v3.14/community/' ;\
+    echo 'https://dl-cdn.alpinelinux.org/alpine/v3.14/main/' ; \
+    echo 'https://dl-cdn.alpinelinux.org/alpine/v3.14/community/' ; \
+    } >/etc/apk/repositories \
+    && cat /etc/apk/repositories \
+    && sleep 5 \
+    && apk update --update-cache \
+    && sleep 5 \
+    && apk upgrade --available \
+    && sleep 5 \
```
Comment (miyoyo) [inline Dockerfile:58]: These sleep commands are not required, bash writes to files synchroneously, and apk blocks until it's complete.

As specified in [the Alpine wiki](https://wiki.alpinelinux.org/wiki/Edge), these two apk commands can be folded into a single command.

Line 53 to Line 58 should be
```
&& apk update --update-cache --available \
```

File: Dockerfile [hunk 3]
```diff
@@ -1,161 +1,101 @@
...
+    && apk add --allow-untrusted curl su-exec tzdata postfix mailx bash openssh supervisor openvas@custcom openvas-smb@custcom openvas-config@custcom gvmd@custcom gvm-libs@custcom greenbone-security-assistant@custcom ospd-openvas@custcom \
+    && mkdir -p /var/log/supervisor/ \
+    && su -c "mkdir /var/lib/gvm/.ssh/ && chmod 700 /var/lib/gvm/.ssh/ && touch /var/lib/gvm/.ssh/authorized_keys && chmod 644 /var/lib/gvm/.ssh/authorized_keys" gvm \
+    && sync
```
Comment (miyoyo) [inline Dockerfile:62]: Docker's build already performs a sync for you between layers, as it has to save it.

File: scripts/start.sh [hunk 4]
```diff
@@ -1,9 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash
```
Comment (miyoyo) [inline scripts/start.sh:1]: While alpine likely will always have bash at `/bin/bash`, `/usr/bin/env bash` is the more portable form.

File: scripts/start.sh [hunk 5]
```diff
@@ -13,308 +16,251 @@ TZ=${TZ:-UTC}
...
-if [ ! -h /usr/local/var/lib/gvm/data-objects ]; then
-	echo "Fixing GVMd Data Objects folder..."
-	
-	rm -rf /usr/local/var/lib/gvm/data-objects
-	
-	ln -s /data/data-objects /usr/local/var/lib/gvm/data-objects
-	
-	chown gvm:gvm -R /data/data-objects
-	chown gvm:gvm -R /usr/local/var/lib/gvm/data-objects
+if [ ! -f "/var/lib/gvm/.firstsync" ]; then
```
Comment (miyoyo) [inline scripts/start.sh:174]: This is gated twice, once here and once in the script it's gating.

Either fold the other script in this one, to clearly indicate that this is not something intended to be run by the user, or run it unconditionally here.

File: scripts/start.sh [hunk 6]
```diff
@@ -326,30 +272,39 @@ if [ $SSHD == "true" ]; then
...
 echo "-----------------------------------------------------------"
-echo ""
-echo "++++++++++++++++"
-echo "+ Tailing logs +"
-echo "++++++++++++++++"
-tail -F /usr/local/var/log/gvm/*
+echo "-----------------------------------------------------------"
+echo "+        Find logs at: /var/log/supervisor/               +"
+echo "+              and at: /usr/local/var/log/gvm/            +"
+echo "==========================================================="
```
Comment (miyoyo) [inline scripts/start.sh:310]: This would encourage people to dig into their containers to get basic log information, contrary to the current status quo, which is to show all logs into stdout, to allow for `docker logs` to work.

Prefer using supervisor's log facilities to display logs to stdout.

Comment (Dexus) [reply scripts/start.sh:310]: That is something I don't like to do, because you get output of all services mixed up and this helps nobody.

This should never ever done in a multi service container! Only if you can separate each log to it's service. What it is not yet done.

File: Dockerfile (hunk 1 above)
Comment (miyoyo) [reply Dockerfile:59]: Here's the breakdown of the packages if required:

```
# Base GVM Packages
gvmd
greenbone-security-assistant
openvas
gvm-tools
# GVM-Provided extensions
openvas-smb
ospd-openvas
py3-gvm
# Report generation
texlive
# HTML Reports
libxslt
xmlstarlet
zip
# Credential packages
fakeroot
# Credential RPM Packages
rpm
# Credential DEB Packages
dpkg
# Credential EXE Packages
# I do not know what is required for nsis generation :/
# Signature verification / S/MIME support
gnupg
# HTTP Alerts
wget
# SCP Alerts
openssh
sshpass
# Send Alerts
socat
# SNMP Alerts
net-snmp-tools
# SMB Alerts
samba-client
# Tipping point Alerts
py3-lxml
# Certificate generation
gnutls-utils
# Lower sync ram usage
perl-xml-twig
```

File: scripts/start.sh (hunk 6 above)
Comment (miyoyo) [reply scripts/start.sh:310]: Understandable, however, this is still a massive behavior change, one that likely will break some workflows relying on log parsing.

This should be pointed out in the first post, as this is a major breaking change that is not linked to the work of switching to alpine.

File: Dockerfile (hunk 1 above)
Comment (Dexus) [reply Dockerfile:59]: You are right, some packages missing while not need and only used to build, some othere could be added, to use optional features. I will have a look to that.

File: Dockerfile (hunk 2 above)
Comment (Dexus) [reply Dockerfile:58]: The sleep is there because sometimes, it would else break the build.

It can be shorten thats correct.

File: scripts/start.sh (hunk 5 above)
Comment (Dexus) [reply scripts/start.sh:174]: Thats correct and is a check on stage1 to prevent a multi run on restart etc. on stage2 it should prevent the manual running of the script it self.
So I don't see there any need to change that as it is also in the current image the same.

Comment (miyoyo) [reply scripts/start.sh:174]: This is part of the "Clean up start.sh" milestone, so this is within the scope of refactoring.

The condition currently shown is
`if [ ! -f "/var/lib/gvm/.firstsync" ]; then`
The condition in the script is
`if [ ! -f "/var/lib/gvm/.firstsync" ] && [ -f "/opt/gvm-sync-data.tar.xz" ]; then`

This is effectively the same as
`if [ ! -f "/var/lib/gvm/.firstsync" ] && [ ! -f "/var/lib/gvm/.firstsync" ] && [ -f "/opt/gvm-sync-data.tar.xz" ]; then`

Which is redundant, the `prevent a multi run on restart etc.` is also accomplished by the second one, using the same condition.

File: Dockerfile (hunk 1 above)
Comment (Dexus) [reply Dockerfile:59]: Here a list of all Packages you mention earlier and there status:

# Base GVM Packages
- [x] gvmd
- [x] greenbone-security-assistant
- [x] openvas
- [x] gvm-tools
# GVM-Provided extensions
- [x] openvas-smb
- [x] ospd-openvas
- [x] py3-gvm
# Report generation
- [ ] texlive
# HTML Reports
- [ ] libxslt
- [ ] xmlstarlet
- [ ] zip
# Credential packages
- [ ] fakeroot
  - Not need
# Credential RPM Packages
- [ ] rpm
  - Not need
# Credential DEB Packages
- [ ] dpkg
  - Not need
# Credential EXE Packages
- I do not know what is required for nsis generation :/
- Not need
# Signature verification / S/MIME support
- [x] gnupg
# HTTP Alerts
- [x] wget
- [x] curl
# SCP Alerts
- [x] openssh
- [ ] sshpass
- [ ] scp
# Send Alerts
- [ ] socat
# SNMP Alerts
- [ ] net-snmp-tools
# SMB Alerts
- [ ] samba-client
# Tipping point Alerts
- [ ] py3-lxml
# Certificate generation
- [x] gnutls-utils
# Lower sync ram usage
- [x] perl-xml-twig

Comment (miyoyo) [reply Dockerfile:59]: For reference, Sourced from: https://github.com/greenbone/gvmd/blob/master/INSTALL.md#prerequisites-for-optional-features

**Review by austinsonger — APPROVED** [review]

**Review by pixelsquared — APPROVED** [review]
I think we can merge into master to get more eyes on it for testing.

I will merge it by the end of day if no one else has any issues.

**Comment by Dexus** [comment]
> I think we can merge into master to get more eyes on it for testing.

I think we should wait one more day, have problems to build the Image because of texlive and will check if I also need to rebuild this.

**Comment by pixelsquared** [comment]
@Dexus Ok then we can wait.

**Comment by austinsonger** [comment]
@Dexus If you want to can make a pull request for `dev` branch and then just work off the `dev`, I gave you write permissions on that branch and just make new pull request when you think its ready to go. But that's up to you.
